media:
  input: public/images
  output: /images

content:
  - name: articoli
    label: Articoli del Blog
    type: collection
    path: content/posts
    fields:
      - name: title
        label: Titolo dell'articolo
        type: string
        required: true
      - name: category
        label: Categoria
        type: select
        options:
          values:
            - Tecnologie
            - Viaggi
            - Vita Personale
            - Tutorial
        required: true
      - name: date
        label: Data
        type: date
        required: true
      - name: body
        label: Contenuto dell'articolo
        type: rich-text
